spring:
  application:
    name: java-bank

  threads:
    virtual:
      enabled: true
  
  datasource:
    url: ${PG_URL_DOCKER}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      dll-auto: none