spring:
  application:
    name: java-bank

  threads:
    virtual:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///java-bank;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: bank
    password:
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level: 
    org:
      springframework:
        data:
          r2dbc: DEBUG
